const mongoose = require('mongoose');

const ReportSchema = new mongoose.Schema({
  fullName: String,
  age: Number,
  dob: Date,
  postAppliedFor: String,
  height: String,
  weight: String,
  gender: String,
  maritalStatus: String,
  passportNo: String,
  placeOfIssue: String,
  dateOfIssue: Date,
  nationality: { type: String, default: 'Indian' },
  passportImage: String,
  medical: {
    visionRight: String,
    visionLeft: String,
    earRight: String,
    earLeft: String,
    bloodPressure: String,
    heartRate: String,
    lungs: String,
    abdomen: String,
    hydrocele: String,
    vdrlTpha: String,
    chestXray: String,
    pregnancy: String,
    remarks: String,
  },
  laboratory: {
    urineSugar: String,
    urineAlbumin: String,
    urineOthers: String,
    haemoglobin: Number,
    malariaRapid: String,
    microfilaria: String,
    bloodGroup: String,
    stoolSalmonella: String,
    stoolBilharziasis: String,
    stoolHelminths: String,
    stoolCholera: String,
    hbsAg: String,
    antiHcv: String,
    hiv: String,
    urea: Number,
    creatinine: Number,
    bloodUrea: Number,
    kft: String,
  },
  fitStatus: String,
  pdfUrl: String,
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Report', ReportSchema);